### ISSUE TITLE
The Footer

### ISSUE THREAD

**Issue by daliaJR** [daliaJR/capstone-project#2]
## Summary

Brief explanation of the feature (task).

### Screenshots
If applicable, add screenshots to help explain the feature.

### Constriants / Details
What are the constraints for this feature. If there is any more details add below.

**Comment by noor-ridha** [comment]
Hi Dalia I wish you're doing well,
Will have a meeting tonight?
I'm actually still out trying to get a cab home but it's a rushing hour and
the roads are so crowded, I'm afraid I can't make it home on time.
Is it possible to reschedule? I will be home around 9 pm .
I don't have access to my discord right now since I don't have my laptop
with me at the moment .
Best Regards
